spring:
  application:
    name: dascribs
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /


app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION_MS} # 24 hours
  security:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
    session:
      timeout-minutes: 120  # 2 hours
      max-sessions-per-user: 5
      cleanup-cron: "0 0 2 * * ?"  # Daily at 2 AM
  public-endpoints:
    - "/api/auth/login"
    - "/api/auth/register"
    - "/api/auth/forgot-password"
    - "/api/auth/reset-password"
    - "/api/public/**"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"

logging:
  level:
    com.dascribs: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always